# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

# https://daniel-krzyczkowski.github.io/Parameters-In-Azure-DevOps-Pipelines/

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build_and_Push_UI_Image
  jobs:
  - job: Build_and_Push_Image
    displayName: Build & Push Image
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build UI Image
      inputs:
        containerRegistry: 'Azure-DoIt-Container-registry'
        repository: 'djeff/doit-ui'
        command: 'build'
        Dockerfile: '**/Dockerfile.ui'
        tags: '$(tag)'
    - task: Docker@2
      displayName: Push API Image
      inputs:
        containerRegistry: 'Azure-DoIt-Container-registry'
        repository: 'djeff/doit-ui'
        command: 'push'
  - job: Set_Artifacts
    displayName: Set Artifacts
    steps:          
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            mkdir $(Build.ArtifactStagingDirectory)/Variables
            echo "$(tag)" > $(Build.ArtifactStagingDirectory)/Variables/Version.variable
            echo "$(Build.ArtifactStagingDirectory)/Variables/Version.variable"
        displayName: 'Create Variable Files'
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)/Variables'
          ArtifactName: 'Variables'
          publishLocation: 'Container'
        displayName: 'Publish Variables Artifact'
      - task: CopyFiles@2
        displayName: Copying directory
        inputs:
          SourceFolder: '$(System.DefaultWorkingDirectory)/docker-info'
          Contents: '**'
          TargetFolder: '$(Build.ArtifactStagingDirectory)'
      - task: PublishBuildArtifacts@1
        displayName: Publish artifacts
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'docker-info'
          publishLocation: 'Container'