# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build API image
      inputs:
        containerRegistry: 'doit-api'
        repository: 'djeff/doit-api'
        command: 'build'
        Dockerfile: '**/Dockerfile.api.local'
        tags: '$(tag)'
    - task: Docker@2
      inputs:
        containerRegistry: 'doit-api'
        command: 'login'
    - task: Docker@2
      inputs:
        containerRegistry: 'doit-api'
        repository: 'djeff/doit-api'
        command: 'push'
# - stage: Test
#   displayName: Test
#   jobs:
#     - job: 
